
Hello {X_UNAME},

There has been a modification to the information regarding "{X_ITEM_NAME}".

Click on the link below to view the dog:
{X_ITEM_URL}

-----------
{X_SITENAME} ({X_SITEURL}) 
administrator/webmaster
{X_ADMINMAIL}


---------------------------------
When this notification has been sent in error or you do no longer wish to use the service you may click on the link below and change your preferences.
{X_UNSUBSCRIBE_URL}
---------------------------------
This message has been generated by the website; there is no point in responding to this message.